/* eslint-disable @typescript-eslint/no-namespace */

/** This file is generated by json-schema-generator.js program **/

import JsonSchemas from './json-schemas.json'

export namespace Schemas {
  export const IndividualQuote = JsonSchemas.IndividualQuote
  export const IndividualQuoteResultFailed = JsonSchemas.IndividualQuoteResultFailed
  export const IndividualQuoteResultSuccess = JsonSchemas.IndividualQuoteResultSuccess
  export const IndividualTransfer = JsonSchemas.IndividualTransfer
  export const IndividualTransferResult = JsonSchemas.IndividualTransferResult
  export const amountCurrency = JsonSchemas.amountCurrency
  export const amountType = JsonSchemas.amountType
  export const bulkQuoteId = JsonSchemas.bulkQuoteId
  export const bulkQuoteRequest = JsonSchemas.bulkQuoteRequest
  export const bulkQuoteResponse = JsonSchemas.bulkQuoteResponse
  export const bulkTransferId = JsonSchemas.bulkTransferId
  export const bulkTransferRequest = JsonSchemas.bulkTransferRequest
  export const bulkTransferResponse = JsonSchemas.bulkTransferResponse
  export const currency = JsonSchemas.currency
  export const dateOfBirth = JsonSchemas.dateOfBirth
  export const errorResponse = JsonSchemas.errorResponse
  export const extensionItem = JsonSchemas.extensionItem
  export const extensionList = JsonSchemas.extensionList
  export const extensionListComplex = JsonSchemas.extensionListComplex
  export const transferError = JsonSchemas.transferError
  export const generalError = JsonSchemas.generalError
  export const mojaloopError = JsonSchemas.mojaloopError
  export const errorInformation = JsonSchemas.errorInformation
  export const errorCode = JsonSchemas.errorCode
  export const errorDescription = JsonSchemas.errorDescription
  export const fspId = JsonSchemas.fspId
  export const fulfilNotification = JsonSchemas.fulfilNotification
  export const geoCode = JsonSchemas.geoCode
  export const idType = JsonSchemas.idType
  export const ID = JsonSchemas.ID
  export const ilpFulfilment = JsonSchemas.ilpFulfilment
  export const ilpPacketData = JsonSchemas.ilpPacketData
  export const initiator = JsonSchemas.initiator
  export const initiatorType = JsonSchemas.initiatorType
  export const latitude = JsonSchemas.latitude
  export const longitude = JsonSchemas.longitude
  export const money = JsonSchemas.money
  export const otpDetails = JsonSchemas.otpDetails
  export const participantsResponse = JsonSchemas.participantsResponse
  export const payerType = JsonSchemas.payerType
  export const quoteId = JsonSchemas.quoteId
  export const quoteRequest = JsonSchemas.quoteRequest
  export const quoteResponse = JsonSchemas.quoteResponse
  export const idSubValue = JsonSchemas.idSubValue
  export const scenario = JsonSchemas.scenario
  export const timestamp = JsonSchemas.timestamp
  export const transactionId = JsonSchemas.transactionId
  export const transactionTypeObject = JsonSchemas.transactionTypeObject
  export const transferDetailsResponse = JsonSchemas.transferDetailsResponse
  export const transferId = JsonSchemas.transferId
  export const transactionRequest = JsonSchemas.transactionRequest
  export const transactionRequestId = JsonSchemas.transactionRequestId
  export const transactionRequestResponse = JsonSchemas.transactionRequestResponse
  export const transactionRequestState = JsonSchemas.transactionRequestState
  export const transactionType = JsonSchemas.transactionType
  export const transferParty = JsonSchemas.transferParty
  export const transferRequest = JsonSchemas.transferRequest
  export const transferResponse = JsonSchemas.transferResponse
  export const transferState = JsonSchemas.transferState
  export const transferStatus = JsonSchemas.transferStatus
}
