/*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

 Contributors
 --------------
 This is the official list (alphabetical ordering) of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.

 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>
 * Modusbox
 - Vijay Kumar Guthi <vijaya.guthi@modusbox.com>

 --------------
 ******/

'use strict'

import fs from 'fs'
// import path from 'path'
import $RefParser from '@apidevtools/json-schema-ref-parser'

const myArgs = process.argv.slice(2)
if (myArgs.length !== 2) {
  console.log('Usage: json-scheme-generator.js <openapi-spec-file> <output-folder>')
  process.exit(1)
}

const openApiFile = myArgs[0]
const outputFolder = myArgs[1]

// console.log(file)
$RefParser.dereference(openApiFile, (err, openApiSpecObj) => {
  if (err) {
    console.error(err)
    process.exit(1)
  }
  const openApiSpec: any = openApiSpecObj
  if (openApiSpec?.components?.schemas) {
    // Write json file for schemas
    fs.writeFile(
      outputFolder + '/json-schemas.json',
      JSON.stringify(openApiSpec?.components?.schemas, null, 2),
      (err1) => {
        if (err1) {
          console.error(err1)
        }
      }
    )
    // Construct schemas file content
    let indexFileContent = '/* eslint-disable @typescript-eslint/no-namespace */'
    indexFileContent += '\n'
    indexFileContent += '\n' + '/** This file is generated by json-schema-generator.js program **/\n'
    indexFileContent += '\n' + "import JsonSchemas from './json-schemas.json'"
    indexFileContent += '\n'
    indexFileContent += '\n' + 'export namespace Schemas {'
    Object.keys(openApiSpec?.components?.schemas).forEach((schemaName) => {
      // Replace - with _
      const newSchemaName = schemaName.replaceAll('-', '_')
      indexFileContent += '\n' + `  export const ${newSchemaName} = JsonSchemas["${schemaName}"]`
    })
    indexFileContent += '\n' + '}'
    indexFileContent += '\n'
    // Write schemas file
    fs.writeFile(outputFolder + '/schemas.ts', indexFileContent, (err1) => {
      if (err1) {
        console.error(err1)
      }
    })

    // Construct types file content
    let typesFileContent = '/* eslint-disable @typescript-eslint/no-namespace */'
    typesFileContent += '\n'
    typesFileContent += '\n' + '/** This file is generated by json-schema-generator.js program **/\n'
    typesFileContent += '\n' + "import { components } from './openapi'"
    typesFileContent += '\n'
    typesFileContent += '\n' + 'export namespace Types {'
    Object.keys(openApiSpec?.components?.schemas).forEach((schemaName) => {
      // Replace - with _
      const newSchemaName = schemaName.replaceAll('-', '_')
      typesFileContent += '\n' + `  export type ${newSchemaName} = components['schemas']['${schemaName}']`
    })
    typesFileContent += '\n' + '}'
    typesFileContent += '\n'
    // Write types file
    fs.writeFile(outputFolder + '/types.ts', typesFileContent, (err1) => {
      if (err1) {
        console.error(err1)
      }
    })
  } else {
    console.log('Can not find .components.schemas in the openAPI file')
    process.exit(1)
  }
})
