openapi: 3.0.2
info:
  $ref: ./info/index.yaml
servers:
  - url: '{protocol}://hostname:<port>/switch/'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
components:
  schemas:
    $ref: ./schemas/index.yaml
  parameters:
    $ref: ./parameters/index.yaml
  headers:
    $ref: ./headers/index.yaml
  responses:
    $ref: ./responses/index.yaml
paths:
  /test:
    get:
      summary: Get server test status
      description: The HTTP request GET /test is used to return the current status of the API.
      operationId: getTest
      responses:
        $ref: ./template/ResponseSetAccepted.yaml
    put:
      summary: Put server test status
      description: The HTTP request GET /test is used to return the current status of the API.
      operationId: putTest
      responses:
        $ref: ./template/ResponseSetOk.yaml
