openapi: 3.0.2
info:
  $ref: ./info/index.yaml
servers:
  - url: '{protocol}://hostname:<port>/switch/'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
components:
  schemas:
    $ref: ./schemas/index.yaml
  parameters:
    $ref: ./parameters/index.yaml
  headers:
    $ref: ./headers/index.yaml
  responses:
    $ref: ./responses/index.yaml
paths:
  /health:
    get:
      summary: This path is for demonstration purposes.
      description: A valid OpenApi3 specification requires `paths` to be defined.
      responses:
        202:
          $ref: './responses/index.yaml#/202'
        400:
          $ref: './responses/index.yaml#/400'
        401:
          $ref: './responses/index.yaml#/401'
        403:
          $ref: './responses/index.yaml#/403'
        404:
          $ref: './responses/index.yaml#/404'
        405:
          $ref: './responses/index.yaml#/405'
        406:
          $ref: './responses/index.yaml#/406'
        501:
          $ref: './responses/index.yaml#/501'
        503:
          $ref: './responses/index.yaml#/503'
